name: Test

on:
  workflow_dispatch:

jobs:
  Test:
    name: Test some stuff
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -l
      - run: go run main.go    
