name: Test

on:
  workflow_dispatch:

jobs:
  Test:
    name: Test some stuff
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: pwd
      - run: ls -l
      - run: go run main.go    
